about us
DmitriyUshkvarok/cats-with-glasses pull request #1
Opened 2022-10-07 13:48 UTC by derofeeva2023

Верстка+мобильный+таблетка. У меня не подтягиваются медиаправила для таблетки, надо смотреть в чем дело. 
Иконка на кнопке - уже пробовала по-разному, не соответствует макету

2022-10-07 17:10 UTC, DmitriyUshkvarok requested changes

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-style: normal;
это не нужно!по умолчанию норм

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-style: normal;
тоже не нужно

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-weight: 400;
жирность по умолчанию 400!удаляй

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +    top: 21.82px;
такие проценты никто не пишет!округляй

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-family: 'Montserrat';
переменная

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-style: normal;
аналогично выше

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-weight: 400;
убирай

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  display: flex;
миксин есть для центровки

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  font-family: 'Montserrat';
переменная

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +  .container {
в глобальных стилях контейнеру пиши переломы!они там останутся для нас всех

2022-10-07 17:10 UTC, DmitriyUshkvarok commented on src/sass/components/_about.scss
> +.about-section__label
пустое свойство

2022-10-07 17:51 UTC, derofeeva2023 commented on src/partials/about.html
> +        <p class="about-section__label">tradition and love</p>
в каком именно файле глобальные стили на эти заголовки?

2022-10-07 17:52 UTC, derofeeva2023 commented on src/partials/about.html
> +        <h2 class="about-section__title_h2">how it’s made?</h2>
в каком именно файле глобальные стили на эти заголовки?

2022-10-07 17:52 UTC, derofeeva2023 commented on src/partials/about.html
> +                    <p>Ice is a place where you will become not
до проверки ментром оставляю так, частично текста нет в макете, возможно баг

2022-10-07 17:54 UTC, derofeeva2023 commented on src/sass/components/_about.scss
> +  font-family: 'Montserrat';
?

2022-10-07 18:20 UTC, DmitriyUshkvarok commented on src/partials/about.html
> +        <p class="about-section__label">tradition and love</p>
title-site.scss

2022-10-07 18:20 UTC, DmitriyUshkvarok commented on src/partials/about.html
> +        <h2 class="about-section__title_h2">how it’s made?</h2>
там же

2022-10-08 08:47 UTC, DmitriyUshkvarok approved these changes

2022-10-08 08:54 UTC, DmitriyUshkvarok approved these changes

2022-10-08 09:30 UTC, merged